[package]
name = "create_cpp_app"
version = "0.1.0"
authors = ["andreico123 <andreicovaci123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termimad = "0.5"
clap = "3.0.0-beta.2"
git2 = "0.13.14"
